micronaut:
  application:
    name: micronaut-experiments

  metrics:
    enabled: true

    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

    binders:
      web:
        enabled: false
      files:
        enabled: false
      logback:
        enabled: false
      processor:
        enabled: false
      uptime:
        enabled: false
      jvm:
        enabled: false
      executor:
        enabled: false

  caches:
    mycache:
      expire-after-write: 11s

endpoints:
  metrics:
    enabled: false
  prometheus:
    enabled: true
    sensitive: false
